export const RESERVE_APPOINTMENT_REQUEST = "RESERVE_APPOINTMENT_REQUEST";
export const RESERVE_APPOINTMENT_SUCCESS = "RESERVE_APPOINTMENT_SUCCESS";
export const RESERVE_APPOINTMENT_FAIL = "RESERVE_APPOINTMENT_FAIL";
export const RESERVE_APPOINTMENT_CLEAR = "RESERVE_APPOINTMENT_CLEAR";
